// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Filters: typeof import('./src/components/Filters.vue')['default']
    'Filters.vue': typeof import('./src/components/Filters.vue.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Map: typeof import('./src/components/Map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    'Table copy': typeof import('./src/components/Table copy.vue')['default']
    TableHeader: typeof import('./src/components/TableHeader.vue')['default']
  }
}

export {}
